name: Deploy Documentation

on:
  push:
    branches:
      - dev

jobs:
  deploy-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up graphviz
      run: sudo apt-get install graphviz

    - name: Set up Doxygen
      run: sudo apt-get install doxygen -y

    - name: Clean output directory
      run: rm -rf ./public/*

    - name: Generate Documentation
      run: doxygen ./docs/Doxyfile

    # - name: Check generated files
    #   run: ls ./public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
